apiVersion: apps/v1
kind: Deployment
metadata:
  name: reparation-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      role: reparation-qa
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: reparation-qa
    spec:
      containers:
        - name: reparation-qa
          image: PROJECT_ID/REPOSITORY/IMAGE
          ports:
            - containerPort: 80