apiVersion: v1
kind: Service
metadata:
  name: reparation-lb-qa
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    role: reparation-qa
  type: LoadBalancer
  loadBalancerIP: "34.67.160.99"