apiVersion: apps/v1
kind: Deployment
metadata:
  name: reparation
spec:
  replicas: 1
  selector:
    matchLabels:
      role: reparation
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: reparation
    spec:
      containers:
        - name: reparation
          image: us-central1-docker.pkg.dev/basearchitecture/quickstart-docker-repo/reparation
          ports:
            - containerPort: 80