apiVersion: v1
kind: Service
metadata:
  name: reparation-lb
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    role: reparation
  type: LoadBalancer
  loadBalancerIP: "34.136.161.82"